# Generated by Django 4.2.8 on 2024-04-07 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=16)),
                ('round_end_time', models.DateTimeField()),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.host')),
                ('quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
                ('round_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='livequiz.room')),
            ],
        ),
        migrations.CreateModel(
            name='HostToMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livequiz.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livequiz.room')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.round')),
            ],
        ),
    ]
